export const SET_APP_NAME = "SET_APP_NAME";
export const SET_VEHICLE_SELECTED = "SET_VEHICLE_SELECTED";
export const SET_DATE_SELECTED = "SET_DATE_SELECTED";
export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const SET_USER_TYPE = "SET_USER_TYPE";
export const FETCH_USERS_SUCCEEDED = 'FETCH_USERS_SUCCEEDED'
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED'
